<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Project;
use Doctrine\ORM\EntityRepository;

/**
 * LikeItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeItemRepository extends EntityRepository
{
    public function getLikesForProject(Project $project)
    {
        $likes = $this->findBy([
            'objectType' => "project",
            'objectId' => $project->getId()
        ]);
        return $likes;
    }
}
